package roles

const (
	PLATFORM_ADMIN_ROLE    = "PLATFORM_ADMIN"
	PLATFORM_OPERATOR_ROLE = "PLATFORM_OPERATOR"
	PLATFORM_USER_ROLE     = "PLATFORM_USER"
	COMPANY_ADMIN_ROLE     = "COMPANY_ADMIN"
	COMPANY_DEVELOPER_ROLE = "COMPANY_DEVELOPER"
	COMPANY_OPERATOR_ROLE  = "COMPANY_OPERATOR"
)

const (
	PLATFORM_ROLE_TYPE = "PLATFORM"
	COMPANY_ROLE_TYPE  = "COMPANY"
)
