package requests

const (
	CHAINCODE_INSTALLED_EMAIL_LIST_FAILED         = "bpaas.notification.email_list_chaincode_instantiated.failed"
	EMAIL_INVITE_COMPLETED_SUBJECT                = "bpaas.email.invite.completed"
	EMAIL_INVITE_FAILED_SUBJECT                   = "bpaas.email.invite.failed"
	LIST_COMPLETED_SUBJECT                        = "bpaas.user.list_company.completed"
	LIST_FAILED_SUBJECT                           = "bpaas.user.list_company.failed"
	NOTIFICATION_CHAINCODE_INSTALLED_COMPLETED    = "bpaas.notification.chaincode.instantiated"
	NOTIFICATION_PASSWORD_RESET_SUBJECT           = "bpaas.notification.user.password_reset"
	NOTIFICATION_PLATFORM_USER_CREATED_SUBJECT    = "bpaas.notification.user.platform.created"
	NOTIFICATION_USER_ACTIVATED_SUBJECT           = "bpaas.notification.user.activated"
	NOTIFICATION_USER_CREATED_SUBJECT             = "bpaas.notification.user.created"
	NOTIFICATION_USER_SUSPENDED_SUBJECT           = "bpaas.notification.user.suspended"
	PING_USER_COMPLETED_SUBJECT                   = "bpaas.ping.user.completed"
	PING_USER_FAILED_SUBJECT                      = "bpaas.ping.user.failed"
	PLATFORMUSER_ACTIVATE_COMPLETED_SUBJECT       = "bpaas.platform_user.activate.completed"
	PLATFORMUSER_ACTIVATE_FAILED_SUBJECT          = "bpaas.platform_user.activate.failed"
	PLATFORMUSER_CANCEL_COMPLETED_SUBJECT         = "bpaas.platform_user.cancel.completed"
	PLATFORMUSER_CANCEL_FAILED_SUBJECT            = "bpaas.platform_user.cancel.failed"
	PLATFORMUSER_CREATE_COMPLETED_SUBJECT         = "bpaas.platform_user.create.completed"
	PLATFORMUSER_CREATE_FAILED_SUBJECT            = "bpaas.platform_user.create.failed"
	USER_ACTIVATE_COMPLETED_SUBJECT               = "bpaas.user.activate.completed"
	USER_ACTIVATE_FAILED_SUBJECT                  = "bpaas.user.activate.failed"
	USER_AUTH_COMPLETED_SUBJECT                   = "bpaas.user.auth.completed"
	USER_AUTH_FAILED_SUBJECT                      = "bpaas.user.auth.failed"
	USER_CREATE_COMPLETED_SUBJECT                 = "bpaas.user.create.completed"
	USER_CREATE_FAILED_SUBJECT                    = "bpaas.user.create.failed"
	USER_EMAIL_VERIFICATION_COMPLETED_SUBJECT     = "bpaas.user.verify_email.completed"
	USER_EMAIL_VERIFICATION_FAILED_SUBJECT        = "bpaas.user.verify_email.failed"
	USER_IS_AUTHORIZED_COMPLETED_SUBJECT          = "bpaas.user.is_authorized.completed"
	USER_IS_AUTHORIZED_FAILED_SUBJECT             = "bpaas.user.is_authorized.failed"
	USER_PASSWORD_CONFIRM_RESET_COMPLETED_SUBJECT = "bpaas.user.password.confirm_reset.completed"
	USER_PASSWORD_CONFIRM_RESET_FAILED_SUBJECT    = "bpaas.user.password.confirm_reset.failed"
	USER_PASSWORD_RESET_COMPLETED_SUBJECT         = "bpaas.user.password.reset.completed"
	USER_PASSWORD_RESET_FAILED_SUBJECT            = "bpaas.user.password.reset.failed"
	USER_SUSPEND_COMPLETED_SUBJECT                = "bpaas.user.suspend.completed"
	USER_SUSPEND_FAILED_SUBJECT                   = "bpaas.user.suspend.failed"
	USER_UPDATE_COMPLETED_SUBJECT                 = "bpaas.user.update.completed"
	USER_UPDATE_FAILED_SUBJECT                    = "bpaas.user.update.failed"
	USER_UPDATE_PROFILE_COMPLETED_SUBJECT         = "bpaas.user.update_profile.completed"
	USER_UPDATE_PROFILE_FAILED_SUBJECT            = "bpaas.user.update_profile.failed"
	USER_UPDATE_ROLE_COMPLETED_SUBJECT            = "bpaas.user.update_role.completed"
	USER_UPDATE_ROLE_FAILED_SUBJECT               = "bpaas.user.update_role.failed"
	USER_WHOAMI_COMPLETED_SUBJECT                 = "bpaas.user.whoami.completed"
	USER_WHOAMI_FAILED_SUBJECT                    = "bpaas.user.whoami.failed"
)
