package subjects

const (
	CHAINCODE_INSTALLED_EMAIL_LIST_FAILED = "bpaas.notification.email_list_chaincode_instantiated.failed"
	USER_LIST_COMPANY_COMPLETED           = "bpaas.user.list_company.completed"
	USER_LIST_COMPANY_FAILED              = "bpaas.user.list_company.failed"
	USER_ACTIVATE_COMPLETED               = "bpaas.user.activate.completed"
	USER_ACTIVATE_FAILED                  = "bpaas.user.activate.failed"
	USER_AUTH_COMPLETED                   = "bpaas.user.auth.completed"
	USER_AUTH_FAILED                      = "bpaas.user.auth.failed"
	USER_CREATE_COMPLETED                 = "bpaas.user.create.completed"
	USER_CREATE_FAILED                    = "bpaas.user.create.failed"
	USER_EMAIL_VERIFICATION_COMPLETED     = "bpaas.user.verify_email.completed"
	USER_EMAIL_VERIFICATION_FAILED        = "bpaas.user.verify_email.failed"
	USER_IS_AUTHORIZED_COMPLETED          = "bpaas.user.is_authorized.completed"
	USER_IS_AUTHORIZED_FAILED             = "bpaas.user.is_authorized.failed"
	USER_PASSWORD_CONFIRM_RESET_COMPLETED = "bpaas.user.password.confirm_reset.completed"
	USER_PASSWORD_CONFIRM_RESET_FAILED    = "bpaas.user.password.confirm_reset.failed"
	USER_PASSWORD_RESET_COMPLETED         = "bpaas.user.password.reset.completed"
	USER_PASSWORD_RESET_FAILED            = "bpaas.user.password.reset.failed"
	USER_SUSPEND_COMPLETED                = "bpaas.user.suspend.completed"
	USER_SUSPEND_FAILED                   = "bpaas.user.suspend.failed"
	USER_UPDATE_COMPLETED                 = "bpaas.user.update.completed"
	USER_UPDATE_FAILED                    = "bpaas.user.update.failed"
	USER_UPDATE_PROFILE_COMPLETED         = "bpaas.user.update_profile.completed"
	USER_UPDATE_PROFILE_FAILED            = "bpaas.user.update_profile.failed"
	USER_UPDATE_ROLE_COMPLETED            = "bpaas.user.update_role.completed"
	USER_UPDATE_ROLE_FAILED               = "bpaas.user.update_role.failed"
	USER_WHOAMI_COMPLETED                 = "bpaas.user.whoami.completed"
	USER_WHOAMI_FAILED                    = "bpaas.user.whoami.failed"
)
